package com.disciplineapp;

/**
 * OLTS on 20.08.2017.
 */
public interface Constants {
    int HABIT_BORDER_COUNT = 21;
    int HABIT_LEVEL_1_BORDER_COUNT = 20;
    int HABIT_LEVEL_2_BORDER_COUNT = HABIT_LEVEL_1_BORDER_COUNT * 3;
    int SUPER_HABIT_LEVEL_COUNT = HABIT_LEVEL_2_BORDER_COUNT * 3;
    int MAX_HABIT_LEVEL_COUNT = SUPER_HABIT_LEVEL_COUNT + HABIT_LEVEL_2_BORDER_COUNT;
}
